version: "3.9"

services:
  app:
    profiles: ["dev"]
    container_name: cpp_api_container
    build:
      context: .
      dockerfile: Dockerfile
    working_dir: /work
    env_file:
      - ./.env
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy
    networks:
      - cpp_api
    ports:
      - "8080:8080"

  redis:
    image: redis:alpine
    container_name: cpp_api_redis_container
    restart: on-failure
    healthcheck:
      test: ["CMD", "sh", "-lc", "redis-cli -a ${REDIS_PASSWORD} ping | grep PONG"]
      interval: 5s
      timeout: 2s
      retries: 10
    command:
      - redis-server
      - '--requirepass root_123456'
    volumes:
      - cache:/data
    networks:
      - cpp_api

  db:
    container_name: cpp_api_db_container
    image: postgres:15.0-alpine
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    restart: on-failure
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 5s
      timeout: 3s
      retries: 20
    volumes:
      - db:/var/lib/postgresql/data  
    networks:
      - cpp_api

volumes:
  db:
    driver: local
  cache:
    driver: local

networks:
  cpp_api:
    driver: bridge
